title: Sanaullah Khaskheli
description: Electrical Engineer â†’ AI & Robotics
author: Sanaullah Khaskheli

theme: minima

header_pages:
  - index.md

minima:
  social_links:
    github: sanaullah-khaskheli
